### ISSUE TITLE
SharedServer: PostgreSQL: Setup

### ISSUE THREAD

**Issue by BNeutral** [FedericoAmura/TallerII2016C2TPLinkedIn#44]
Setup para que quede integrado con el código

**Comment by FedericoAmura** [comment]
Ya esta creada la base en postgre, por ahora solo tiene la tabla de categories.
Despues vuelvo y genero el resto metiendole las primaries, foreign, etc. que hacen falta

**Comment by FedericoAmura** [comment]
Hecho
