### ISSUE TITLE
Skills/Jobs con espacios

### ISSUE THREAD

**Issue by BNeutral** [FedericoAmura/TallerII2016C2TPLinkedIn#89]
Al ser pedidos de android al app server, da invalid URI pese a tener los espacios escapados con %20. Antes andaba pero en algun momento se rompio.

**Comment by emanuelcondo** [comment]
ver en AppServer/include/server/API_Server.h si agregando los espacios en los regex funciona

**Comment by BNeutral** [comment]
Sigue andando mal. Ahora lo miro.
